<a href="https://colab.research.google.com/github/HarryAI-6748/ml-project/blob/main/Firstname_Lastname_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

mean_temp = data.mean(axis = 1)
mean_temo_1 = mean_temp[:, np.newaxis]
print("Mean temperature per station")
print(mean_temo_1, end ="\n\n")
high_temp = (data > 28.0)
print("Temperature readings above 28.0°C")
print(data[high_temp], end="\n\n")
x = np.max(data)
y = np.min(data)
z = x - y
normalised = (data - y) / z
normalized = np.round(normalised, 2)
print("Normalized data")
print(normalized)




Mean temperature per station
[[25.3 ]
 [23.78]
 [26.58]
 [25.26]]

Temperature readings above 28.0°C
[31.2 28.7 30.5 33.1 29.6 31.9 28.1]

Normalized data
[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
